.circleci/config.yml, .gitignore, CHANGELOG.md, Dockerfile, README.md, flag/flag.go, go.mod, helm/template-operator/Chart.yaml, helm/template-operator/values.yaml, main.go, pkg/project/project.go, pkg/project/version_bundle.go, server/endpoint/endpoint.go, server/server.go, service/controller/todo.go, service/controller/todo_resource_set.go, service/service.go
=> Rename template-operator into rbac-operator

flag/service/namespaceauth/namespaceauth.go, helm/rbac-operator/templates/rbac-tenant-admin.yaml, helm/rbac-operator/templates/rbac-view-all.yaml, main.go, pkg/project/version_bundle.go, service/controller/resource/namespaceauth/create.go, service/controller/resource/namespaceauth/delete.go, service/controller/resource/namespaceauth/resource.go, service/service.go
Towards https://github.com/giantswarm/giantswarm/issues/9248
=> Add tenant admin access

helm/rbac-operator/templates/configmap.yaml, helm/rbac-operator/templates/deployment.yaml, helm/rbac-operator/templates/psp.yaml, helm/rbac-operator/templates/rbac-tenant-admin.yaml, helm/rbac-operator/templates/rbac-view-all.yaml, helm/rbac-operator/templates/rbac.yaml, helm/rbac-operator/templates/service-account.yaml, helm/rbac-operator/templates/service.yaml, helm/rbac-operator/values.yaml, pkg/project/project.go
=> Do not install resources if disabled

helm/rbac-operator/templates/rbac-tenant-admin.yaml
=> Bring back missing rolebinding

CHANGELOG.md, helm/rbac-operator/templates/deployment.yaml
Towards giantswarm/giantswarm#10098
=> Use release.Revision in Helm chart for Helm 3 support

CHANGELOG.md, service/controller/resource/namespaceauth/create.go
Towards https://github.com/giantswarm/giantswarm/issues/10836
=> Update binding on role change

CHANGELOG.md, pkg/project/project.go
=> Release v0.3.3

.circleci/config.yml, CHANGELOG.md
=> Add push tags to aliyun

CHANGELOG.md, pkg/project/project.go
=> Release v0.4.0

CHANGELOG.md, pkg/project/project.go
=> Release v0.4.1

CHANGELOG.md, service/controller/rbac/rbac.go
Towards https://github.com/giantswarm/roadmap/issues/148
=> Watch organization namespaces

CHANGELOG.md, pkg/project/project.go
=> Release v0.4.2

pkg/project/project.go
=> Bump version to 0.4.2-dev

CHANGELOG.md, helm/rbac-operator/templates/_helpers.tpl, helm/rbac-operator/templates/_resource.tpl, helm/rbac-operator/templates/configmap.yaml, helm/rbac-operator/templates/deployment.yaml, helm/rbac-operator/templates/psp.yaml, helm/rbac-operator/templates/rbac-tenant-admin.yaml, helm/rbac-operator/templates/rbac-view-all.yaml, helm/rbac-operator/templates/rbac.yaml, helm/rbac-operator/templates/service-account.yaml, helm/rbac-operator/templates/service.yaml, helm/rbac-operator/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/11215
=> Refresh Helm chart

.circleci/config.yml
=> circleci: update architect orb to 0.9.0

.circleci/config.yml, CHANGELOG.md, helm/rbac-operator/templates/service-account.yaml, helm/rbac-operator/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/12454
=> Do not run rbac operator

.github/workflows/zz_generated.create_release.yaml, .github/workflows/zz_generated.create_release_pr.yaml, CHANGELOG.md
=> Add release automation github actions

helm/rbac-operator/templates/rbac-tenant-admin.yaml
=> Fix view-all rolebinding for tenant-admin

CHANGELOG.md
=> Update changelog for fixed roleref

CHANGELOG.md, helm/rbac-operator/templates/rbac-tenant-admin.yaml
=> Fix rolebinding CR tenant-admin

.github/dependabot.yml, .github/workflows/zz_generated.gomodtidy.yaml, CHANGELOG.md
=> Add Dependabot

.github/dependabot.yml
=> Bump k8s version in dependabot config

CHANGELOG.md, helm/rbac-operator/templates/service.yaml
=> Add monitoring label

service/controller/rbac/resource/namespaceauth/resource.go
Removed some unnecessary code.
=> Remove unused code

CHANGELOG.md, helm/rbac-operator/ci/default-values.yaml, helm/rbac-operator/templates/rbac-control-plane-admin.yaml
Towards https://github.com/giantswarm/giantswarm/issues/12196
Following https://github.com/giantswarm/installations/pull/1588/files
=> Add cp cluster-admin

CHANGELOG.md, flag/service/namespaceauth/namespaceauth.go, flag/service/service.go, main.go, service/controller/rbac/rbac.go, service/controller/rbac/rbac_resources.go, service/controller/rbac/resource/namespaceauth/create.go, service/controller/rbac/resource/namespaceauth/delete.go, service/controller/rbac/resource/namespaceauth/resource.go, service/service.go
1. Remove view-all only related bindings
2. Refactor controller and make it binding customer admin group to cluster-admin cluster role in target organization
=> Remove read all rolebinding group

helm/rbac-operator/Chart.yaml
Towards giantswarm/giantswarm#14846
Last one. 🙏
=> Add team annotation to Chart.yaml

flag/flag.go, service/controller/orgpermissions/resource/membership/create.go, service/controller/orgpermissions/resource/membership/delete.go, service/controller/orgpermissions/resource/membership/resource.go, service/controller/rbac/resource/namespaceauth/delete.go, service/internal/bootstrap/resources.go
=> Fix go imports

service/controller/orgpermissions/orgpermissions.go, service/controller/orgpermissions/resource/membership/create.go
=> Fix selector for organization namespace

helm/rbac-operator/templates/configmap.yaml
=> Update rbac-operator cm with new groups structure

CHANGELOG.md, service/internal/bootstrap/resources.go
Towards https://github.com/giantswarm/giantswarm/issues/16265
=> Update read-all role on every bootstrap

CHANGELOG.md, helm/rbac-operator/templates/rbac.yaml
=> Fix namespace permissions for rbac-operator clusterrole

.circleci/config.yml
=> push to shared app collection

CHANGELOG.md, pkg/key/key.go, service/internal/bootstrap/bootstrap.go, service/internal/bootstrap/resources.go
=> Label default clusterroles to display in UI

CHANGELOG.md, service/controller/orgpermissions/orgpermissions.go, service/controller/orgpermissions/resource/membership/create.go
=> Remove selector in orgpermissions-controller

pkg/key/key.go, service/controller/orgpermissions/resource/membership/create.go, service/controller/orgpermissions/resource/membership/delete.go
=> Fix role binding to clusterrole

CHANGELOG.md, helm/rbac-operator/templates/configmap.yaml, helm/rbac-operator/templates/deployment.yaml, helm/rbac-operator/templates/psp.yaml, helm/rbac-operator/templates/rbac.yaml, helm/rbac-operator/templates/service.yaml
Towards https://github.com/giantswarm/giantswarm/issues/16455
=> Enable rbac-operator resources installation by default

CHANGELOG.md, service/internal/bootstrap/resources.go
Towards https://github.com/giantswarm/giantswarm/issues/16077
=> Update bootstrap resources on restart

CHANGELOG.md, pkg/key/key.go, service/internal/bootstrap/bootstrap.go, service/internal/bootstrap/resources.go
Towards https://github.com/giantswarm/giantswarm/issues/16932
=> Allow customer admin group to manage organizations

README.md
=> Update rbac-operator README

helm/rbac-operator/Chart.yaml
Towards https://github.com/giantswarm/giantswarm/issues/19760
=> Set team annotation in Chart.yaml for app alert routing

CHANGELOG.md, pkg/key/key.go, service/internal/bootstrap/resources.go
Closes https://github.com/giantswarm/giantswarm/issues/19835
=> Set the 'giantswarm.io/managed-by' label on the default ClusterRoles

CHANGELOG.md, pkg/key/key.go, service/internal/bootstrap/resources.go
=> Add permissions to automation account for silences

CHANGELOG.md, service/internal/bootstrap/bootstrap.go
=> Added missing bootstrap for silences and clientcert automation sa

.circleci/config.yml
Towards https://github.com/giantswarm/giantswarm/issues/20119
=> CI: push to openstack-app-collection

CHANGELOG.md
=> Remove duplicate Changelog entry

CHANGELOG.md, pkg/key/key.go, service/internal/bootstrap/bootstrap.go, service/internal/bootstrap/releases.go
Towards https://github.com/giantswarm/giantswarm/issues/20885
=> add read-releases clusterrole

CHANGELOG.md, pkg/key/key.go, service/internal/bootstrap/bootstrap.go, service/internal/bootstrap/catalog.go
Towards https://github.com/giantswarm/giantswarm/issues/20886
We don't have any spec for this so feel free to request changes.
=> add read default catalogs role

.circleci/config.yml
=> bump architect-orb to v4.13.0

CHANGELOG.md, service/internal/bootstrap/catalog.go, service/internal/bootstrap/releases.go, service/internal/bootstrap/resources.go
This should be the last sweep on logging. Also I touched some role descriptions I came across.
=> Improve logging for the bootstrap part, improve some role descriptions

go.mod, go.sum
=> Fix jwt-go replacement, use Go 1.17

CHANGELOG.md, go.mod, pkg/key/key.go, service/controller/clusternamespace/resource/clusternamespaceresources/common_test.go, service/controller/clusternamespace/resource/clusternamespaceresources/config.go, service/controller/clusternamespace/resource/clusternamespaceresources/create.go, service/controller/clusternamespace/resource/clusternamespaceresources/create_test.go, service/controller/clusternamespace/resource/clusternamespaceresources/delete.go, service/controller/clusternamespace/resource/clusternamespaceresources/delete_test.go, service/controller/clusternamespace/resource/clusternamespaceresources/resource.go, service/controller/rbac/resource/fluxauth/create.go
Towards https://github.com/giantswarm/giantswarm/issues/21792.
Tested on `gauss`. Two additional `RoleBindings` have been created successfully and also removed upon cluster deletion. No `RoleBinding` has been created in unwanted namespace. No errors in the logs.
=> Adding Flux RBAC in cluster ns

CHANGELOG.md, service/controller/clusternamespace/key/key.go, service/controller/clusternamespace/resource/rbaccleaner/create.go, service/controller/clusternamespace/resource/rbaccleaner/create_test.go
Towards: giantswarm/giantswarm#21891
Discussion: https://gigantic.slack.com/archives/C02GDJJ68Q1/p1652808661298139
=> Clean up *chart ClusterRole and ClusterRoleBinding

CHANGELOG.md, pkg/annotation/annotation.go, pkg/key/key.go, service/controller/clusternamespace/resource/clusternamespaceresources/create.go, service/controller/clusternamespace/resource/clusternamespaceresources/error.go
=> retry fetching organizations using legacy org annotation

CHANGELOG.md, pkg/rbac/cluster_role.go, pkg/rbac/cluster_role_binding.go, pkg/rbac/role.go, pkg/rbac/role_binding.go
=> Prevent unnecessary resource updates

helm/rbac-operator/Chart.yaml, helm/rbac-operator/templates/configmap.yaml
=> test multiple admin groups

.circleci/config.yml, .nancy-ignore
=> push to capz app collection

.circleci/config.yml, CHANGELOG.md
=> Remove shared app collection from circle CI

.nancy-ignore, CHANGELOG.md, go.mod
- Updated dependencies with CVEs to the latest versions
- Adjusted nancyignore - removed fixed CVEs & added new ones, which cannot be fixed yet
=> Updated dependencies

helm/rbac-operator/templates/ciliumnetworkpolicy.yaml, helm/rbac-operator/values.schema.json, helm/rbac-operator/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/23014
Towards https://github.com/giantswarm/roadmap/issues/1949
=> Add cilium network policies

CHANGELOG.md, helm/rbac-operator/templates/psp.yaml, helm/rbac-operator/values.schema.json, helm/rbac-operator/values.yaml
Towards [giantswarm/giantswarm#28338](https://github.com/giantswarm/giantswarm/issues/28338)
=> PSP Toggle

CHANGELOG.md, go.mod, go.sum
=> Updated go.sum entries and dependencies

CHANGELOG.md, helm/rbac-operator/templates/ciliumnetworkpolicy.yaml, helm/rbac-operator/values.yaml
towards https://github.com/giantswarm/giantswarm/issues/29581
=> Update CiliumNetworkPolicy and enable by default

CHANGELOG.md, tests/ats/pytest.ini, tests/ats/test_rbac_controller_externalresources.py
Towards: [#31430](https://github.com/giantswarm/giantswarm/issues/31430)
=> Flaky tests improvement

.circleci/config.yml, CHANGELOG.md, tests/ats/test_rbac_controller_externalresources.py
Towards https://github.com/giantswarm/giantswarm/issues/31374
```
trivy image --severity CRITICAL quay.io/giantswarm/rbac-operator:0.41.0-021cbf1748f24af229560eb52176032a54f172b5
2024-07-29T12:36:59+05:45	INFO	Vulnerability scanning is enabled
2024-07-29T12:36:59+05:45	INFO	Secret scanning is enabled
2024-07-29T12:36:59+05:45	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-07-29T12:36:59+05:45	INFO	Please see also https://aquasecurity.github.io/trivy/v0.51/docs/scanner/secret/#recommendation for faster secret detection
2024-07-29T12:37:17+05:45	INFO	Detected OS	family="alpine" version="3.20.1"
2024-07-29T12:37:17+05:45	WARN	This OS version is not on the EOL list	family="alpine" version="3.20"
2024-07-29T12:37:17+05:45	INFO	[alpine] Detecting …
```
=> Bump architect-orb@5.3.1

.nancy-ignore, CHANGELOG.md, flag/service/service.go, helm/rbac-operator/templates/configmap.yaml, service/controller/crossplane/crossplane.go, service/controller/crossplane/crossplane_resources.go, service/controller/defaultnamespace/defaultnamespace.go, service/controller/defaultnamespace/defaultnamespace_resources.go, service/controller/defaultnamespace/defaultnamespace_test.go, service/controller/defaultnamespace/resource/usergroups/create.go, service/controller/defaultnamespace/resource/usergroups/resource.go, service/controller/rbac/rbac.go, service/controller/rbac/rbac_resources.go, service/controller/rbac/resource/namespaceauth/resource.go, service/internal/accessgroup/accessgroup.go, service/service.go, service/service_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/32339
=> Add read-all-customer-group support for ClusterRoleBindings

.circleci/config.yml, .nancy-ignore
=> Bump architect-orb to v5.13.1

CHANGELOG.md, pkg/rbac/cluster_role.go, pkg/rbac/cluster_role_binding.go, pkg/rbac/role.go, pkg/rbac/role_binding.go, service/controller/clusternamespace/resource/clusternamespaceresources/create_test.go, service/controller/defaultnamespace/defaultnamespacetest/test_methods.go, service/controller/rolebindingtemplate/resource/rolebinding/resource.go
=> Resolve golangci-lint v2 problems in rbac-operator
