CHANGELOG.md, helm/rbac-operator/templates/rbac-view-all.yaml
Towards https://github.com/giantswarm/giantswarm/issues/9248
Adding view-all role with access to read/list/watch all the resources except configmaps/secrets
Role is bounded to the group, configured in installations repo e.g. here https://github.com/giantswarm/installations/pull/1095
=> Add readonly cluster role

CHANGELOG.md, helm/rbac-operator/templates/rbac-tenant-admin.yaml
Towards https://github.com/giantswarm/giantswarm/issues/9883
Customers should be able to create serviceaccounts for their automation tooling, which can manage clusters CRs in installation
=> Add rbac manager creds for tenant admin in default namespace

CHANGELOG.md, helm/rbac-operator/templates/deployment.yaml, helm/rbac-operator/templates/rbac.yaml, pkg/label/label.go, service/controller/namespacelabeler/key/error.go, service/controller/namespacelabeler/key/key.go, service/controller/namespacelabeler/namespace_labeler.go, service/controller/namespacelabeler/namespace_labeler_resource_set.go, service/controller/namespacelabeler/resource/namespacelabel/create.go, service/controller/namespacelabeler/resource/namespacelabel/delete.go, service/controller/namespacelabeler/resource/namespacelabel/error.go, service/controller/namespacelabeler/resource/namespacelabel/resource.go, service/service.go
For legacy namespaces, which have labels `cluster`/`customer` - add labels `giantswarm.io/cluster` and `giantswarm.io/organization` so that rbac controller can manage rbac for those namespaces
=> Add namespacelabeler controller

CHANGELOG.md, helm/rbac-operator/templates/rbac-tenant-admin.yaml, pkg/label/label.go, service/controller/rbac/key/key.go, service/controller/rbac/resource/namespaceauth/create.go, service/controller/rbac/resource/namespaceauth/resource.go
Service account `automation` will be created in `global` namespace. It can be used for further rbac management in CI pipelines
=> Add automation serviceaccount

CHANGELOG.md, service/controller/namespacelabeler/namespace_labeler.go
The current selector selects only namespace with empty labels
=> Fix label selector to cover labels with values

CHANGELOG.md, service/controller/rbac/resource/namespaceauth/create.go, service/controller/rbac/resource/namespaceauth/resource.go
With the new binding introduced in recent PRs, role name was set to the rolebinding name. That is wrong. Current PR fixes this.
=> Fix role reference

service/controller/rbac/resource/namespaceauth/create.go
This reverts commit 3b0cc187dfdf99ed0c37b80f341a2950f18c0908.
updating of the role reference is not supported.
I'll manually cleanup affected clusters
=> Revert "Fix update logic"

CHANGELOG.md, service/controller/rbac/resource/namespaceauth/create.go
When a new CRD is added **after** a `Role` has already been created, the role doesn't have enough permissions to work with the new type. We need to update the `Role` when new CRDs are added.
=> Update role rules when they are not up to date

pkg/key/key.go, service/controller/orgpermissions/key/error.go, service/controller/orgpermissions/key/key.go, service/controller/orgpermissions/orgpermissions.go, service/controller/orgpermissions/orgpermissions_resources.go, service/controller/orgpermissions/resource/membership/create.go, service/controller/orgpermissions/resource/membership/delete.go, service/controller/orgpermissions/resource/membership/error.go, service/controller/orgpermissions/resource/membership/resource.go, service/controller/rbac/resource/namespaceauth/create.go, service/controller/rbac/resource/namespaceauth/delete.go, service/service.go
Towards https://github.com/giantswarm/giantswarm/issues/16060
1. For every organization namespace, there is clusterrole with name `<org>-organization-read` created with the following access:
```
rules:
- apiGroups:
- security.giantswarm.io
resourceNames:
- <org>
resources:
- organizations
verbs:
- get
```
2. For every rolebinding in organization namespace, where subject is Group or User, new rolebinding with name `<source binding>-organization-read` is created, where subjects are the same as in orgininal rolebinding and clusterrole is from *1*
=> Add binding controller

CHANGELOG.md, pkg/key/key.go, service/internal/bootstrap/bootstrap.go, service/internal/bootstrap/resources.go
Closes https://github.com/giantswarm/roadmap/issues/534
Turns out the customer asked for access to more CRs than I initially thought. So we have all the `flux` resources, as well as all cluster and node pool specific resources.
=> Allow automation to edit flux and cluster-specific CRs

CHANGELOG.md, pkg/key/key.go, service/internal/bootstrap/resources.go
Customers need to be able to create WC client certificates using the `automation` ServiceAccount.
=> Add permission for WC cert creation to the automation SA

CHANGELOG.md, go.mod, go.sum, service/internal/bootstrap/resources.go
Towards https://github.com/giantswarm/roadmap/issues/602
This applies the annotation `giantswarm.io/notes` to created ClusterRole resources, in order to provide user-friendly descriptions for all cluster roles.
=> Add user-friendly descriptions to ClusterRole resources

.github/pull_request_template.md, CHANGELOG.md
Closes https://github.com/giantswarm/roadmap/issues/602.
This PR updates the PR template by adding an item to the checklist as a reminder to add description annotations if the PR introduces new roles.
=> Add checklist item to PR template for role description annotation

CHANGELOG.md, service/controller/orgpermissions/resource/membership/create.go
Towards https://github.com/giantswarm/roadmap/issues/766
=> Add update option for orgReadClusterRoleBinding resource

CHANGELOG.md, service/controller/clusternamespace/resource/clusternamespaceresources/create.go, service/controller/clusternamespace/resource/clusternamespaceresources/delete.go
Draft to illustrate how I would like the controllers to log.
- Don't produce a log line if nothing is done.
- If something is happening, use level `info`.
- Try to make the log messages as useful as possible, e. g. by providing the namespace where it's relevant.
=> Improve logging in clusternamespace controller

CHANGELOG.md, service/controller/orgpermissions/resource/membership/create.go, service/controller/orgpermissions/resource/membership/delete.go
=> Clean up logging in orgpermissions controller

CHANGELOG.md, pkg/key/key.go, service/controller/rbac/resource/externalresources/create.go, service/controller/rbac/resource/externalresources/delete.go, service/controller/rbac/resource/externalresources/resource.go, service/controller/rbac/resource/fluxauth/create.go, service/controller/rbac/resource/fluxauth/delete.go, service/internal/bootstrap/clusternamespace.go
Towards https://github.com/giantswarm/giantswarm/issues/21089
=> dynamically bind read/write in cluster namespace roles for read-all and cluster-admin users

CHANGELOG.md, pkg/key/key.go, service/controller/orgpermissions/resource/membership/create.go, service/controller/rbac/resource/externalresources/create.go, service/controller/rbac/resource/externalresources/delete.go
Towards https://github.com/giantswarm/giantswarm/issues/21477
The `orgpermissions` controller reconciles `rolebindings` in the org namespace and creates one `clusterrolebinding` for each of them that gives the subjects read-access to the organization cr by name.
This is messy as it creates a lot of `clusterrolebindings` and also does not work for rolebindings wmanaged by the operator itself.
This PR replaces the old controller by creating just one rolebinding for all the subjects. Since we already have similar logic for access to releases there I have added this to the `externalresources`.
Also this deprecates the `orgpermissions` controller. For now the creation logic is removed and I want to see if we can use it to clean up the existing clusterrolebindings since they will be hard to …
=> replace orgpermissions with externalresources

CHANGELOG.md, service/internal/bootstrap/bootstrap.go, service/internal/bootstrap/resources.go
Towards: https://github.com/giantswarm/giantswarm/issues/22096
=> Removing `ClusterRoleBinding` for `default:automation` SA

.nancy-ignore, CHANGELOG.md, service/internal/bootstrap/resources.go
This PR introduces pods/log access to enable customers to troubleshoot issues on the management clusters themselves.
Aims to satisfy:
- https://github.com/giantswarm/giantswarm/issues/24033
- https://github.com/giantswarm/roadmap/issues/948
=> Add pod logs

.gitignore, flag/service/service.go, go.mod, helm/rbac-operator/templates/configmap.yaml, main.go, service/controller/clusternamespace/resource/clusternamespaceresources/create.go, service/controller/rbac/rbac.go, service/controller/rbac/rbac_resources.go, service/controller/rbac/resource/namespaceauth/create.go, service/controller/rbac/resource/namespaceauth/resource.go, service/internal/accessgroup/accessgroup.go, service/internal/accessgroup/accessgroup_test.go, service/internal/bootstrap/bootstrap.go, service/internal/bootstrap/bootstrap_test.go, service/internal/bootstrap/resources.go, service/service.go, service/service_test.go
Added support for creating roles for multiple admin roles defined in the config map.
The config map supports new properties in the `service` section to define multiple entries for each known admin group type:
```yaml
service:
accessGroups:
writeAllCustomerGroups:
- name: customer:giantswarm:Employees1
- name: customer:giantswarm:Employees2
writeAllGiantswarmGroups:
- name: giantswarm:giantswarm:giantswarm-admins1
- name: giantswarm:giantswarm:giantswarm-admins2
```
The old way of defining admin groups is also supported and can be combined with the new one:
```yaml
service:
writeAllCustomerGroup: customer:giantswarm:Employees
writeAllGiantswarmGroup: giantswarm:giantswarm:giantswarm-admins
```
The operator will create RoleBindings and ClusterRoleBindings for all admin groups specified in …
=> Added support for multiple admin groups

.abs/main.yaml, .circleci/config.yml, CHANGELOG.md, helm/rbac-operator/Chart.yaml, helm/rbac-operator/templates/_helpers.tpl, helm/rbac-operator/templates/deployment.yaml, helm/rbac-operator/values.schema.json, helm/rbac-operator/values.yaml
This PR migrates rbac-operator to abs. This will make it easier to integrate chart tests and is therefore towards https://github.com/giantswarm/giantswarm/issues/20068
Architect replaced some template values in the `values.yaml`, which abs does not do anymore.
I think that these values were not used for anything. As a reviewer please confirm that.
=> Migrate to app-build-suite

.nancy-ignore, CHANGELOG.md, service/internal/bootstrap/resources.go
When adding `pods/log` rule inside the loop we add it multiple times, so for clarity I think it is better to just move it outside the loop.
=> Fixing pods/log

CHANGELOG.md, helm/rbac-operator/templates/deployment.yaml, helm/rbac-operator/templates/psp.yaml, helm/rbac-operator/values.schema.json, helm/rbac-operator/values.yaml
I've modified the container and pod securitycontexts to let this application make use of the runtime/default seccomp profile. During testing this did not seem to interrupt any functionality. Please confirm this if possible.
This is done in light of:
https://github.com/giantswarm/roadmap/issues/259
Drop a message on slack if you've got questions.
=> Added the use of the runtime/default seccomp profile.

CHANGELOG.md, service/controller/defaultnamespace/resource/clusterroles/create.go, service/controller/defaultnamespace/resource/clusterroles/create_test.go
We add a rule for `pods/log` to the `read-all` ClusterRole policy rules, but it was being added multiple times. This PR moves it outside of the loop, and should solve the issue described in https://github.com/giantswarm/roadmap/issues/2364.
I've tested it on the Azure test installation, but would appreciate if someone with more rbac-operator/Go expertise could take a look
=> Fix appending `pods/log` policy rule to `read-all` ClusterRole

CHANGELOG.md, go.mod
I tried to make a release but the build is failing in CI due to security vulnerabilities with `gin`. This updates it to the recommended version.
=> Update gin dependency

CHANGELOG.md, go.mod, service/controller/clusternamespace/resource/clusternamespaceresources/create_test.go, service/controller/clusternamespace/resource/clusternamespaceresources/delete_test.go, service/controller/rbac/resource/namespaceauth/create.go, service/controller/rbac/resource/namespaceauth/create_test.go, service/test/common.go
In case a new customer admin group is added to the operator, it is not added to the `write-all-customer-group`  role bindings in organization namespaces. 
This PR fixes it and ensures that customer groups in organization namespace role bindings are updated correctly..
More details: https://github.com/giantswarm/roadmap/issues/2418
=> Fixed reconciliation of group subjects in org namespaces

CHANGELOG.md, helm/rbac-operator/templates/deployment.yaml
This PR updates the deployment to be PSS compliant.
Towards https://github.com/giantswarm/giantswarm/issues/27338
Fixed policy violations:
```
policy disallow-capabilities-strict -> resource default/Deployment/release-name failed: 
1. autogen-require-drop-all: validation failure: Containers must drop `ALL` capabilities. 
policy disallow-privilege-escalation -> resource default/Deployment/release-name failed: 
1. autogen-privilege-escalation: validation error: Privilege escalation is disallowed. The fields spec.containers[*].securityContext.allowPrivilegeEscalation, spec.initContainers[*].securityContext.allowPrivilegeEscalation, and spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation must be set to `false`. rule autogen-privilege-escalation failed at path …
```
=> Update deployment to be PSS compliant

api/v1alpha1/rolebindingtemplate_types.go, config/crd/auth.giantswarm.io_rolebindingtemplates.yaml, service/controller/rolebindingtemplate/resource/rolebinding/create.go, service/controller/rolebindingtemplate/resource/rolebinding/create_test.go, service/controller/rolebindingtemplate/resource/rolebinding/resource.go
Towards https://github.com/giantswarm/roadmap/issues/2709
`spec` is not an attribute of roleBindings, so instead of `spec` we reference `roleRef` and `subjects` directly within the template resource.
=> remove rolebindingtemplate.spec.template.spec

CHANGELOG.md, service/controller/rolebindingtemplate/resource/rolebinding/create.go, service/controller/rolebindingtemplate/resource/rolebinding/create_test.go
When a single RoleBindingTemplate needs to be applied to multiple namespaces, subjects of role bindings created from the template may have subjects with incorrect namespaces.
This PR fixes that.
=> Fixed applying RoleBindingTemplate to multiple namespaces

CHANGELOG.md, tests/ats/test_rbac_controller_externalresources.py
On the previous PR by renovate bot the following test failed: `TestRBACControllerExternalResources::test_rbac_controller_external_resources`
I tried it out a couple of times locally and it seems that the test is flaky. 
This PR increases the maximum number of retries from 5 to 10.
=> Fix flaky tests

CHANGELOG.md, go.mod, pkg/key/key.go, pkg/rbac/role_binding.go, service/controller/defaultnamespace/defaultnamespacetest/test_methods.go, service/controller/rbac/resource/namespaceauth/create.go, service/controller/rbac/resource/namespaceauth/create_test.go, service/controller/rolebindingtemplate/resource/rolebinding/create.go, service/controller/rolebindingtemplate/resource/rolebinding/create_test.go
Towards https://github.com/giantswarm/giantswarm/issues/26439
=> restrict access to org-giantswarm namespace

CHANGELOG.md, helm/rbac-operator/values.yaml
Towards
- https://github.com/giantswarm/roadmap/issues/3017
This PR replaces any occurrence of `docker.io` in `values.yaml` files with `gsoci.azurecr.io`,
to make the new ACR registry the default one.
=> Configure gsoci.azurecr.io as the registry to use by default

CHANGELOG.md, pkg/key/key.go, service/controller/defaultnamespace/defaultnamespace_test.go, service/controller/defaultnamespace/resource/usergroups/create.go, service/controller/defaultnamespace/resource/usergroups/create_test.go
Fix missing cluster-wide write permissions for customer admin groups by adding the missing `write-all-customer-group` ClusterRoleBinding.
=> Fix missing cluster-wide write permissions for customer admin groups
